### ISSUE TITLE
Metadata mismatch

### ISSUE THREAD

**Issue by EddWills95** [bergben/ng2-img-max#21]
Tried to fire up my app this morning but I have got this error:

`ERROR in Error: Metadata version mismatch for module /Users/eddwdev/Desktop/Herts/staff-directory/node_modules/ng2-img-max/dist/ng2-img-max.d.ts, found version 4, expected 3, resolving symbol AppModule in /Users/eddwdev/Desktop/Herts/staff-directory/src/app/app.module.ts, resolving symbol AppModule in /Users/eddwdev/Desktop/Herts/staff-directory/src/app/app.module.ts
    at Error (native)
    at syntaxError (/Users/eddwdev/Desktop/Herts/staff-directory/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/eddwdev/Desktop/Herts/staff-directory/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/Users/eddwdev/Desktop/Herts/staff-directory/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/Users/eddwdev/Desktop/Herts/staff-directory/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/Users/eddwdev/Desktop/Herts/staff-directory/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/eddwdev/Desktop/Herts/staff-directory/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Users/eddwdev/Desktop/Herts/staff-directory/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/eddwdev/Desktop/Herts/staff-directory/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/eddwdev/Desktop/Herts/staff-directory/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/eddwdev/Desktop/Herts/staff-directory/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)`

Not sure if anyone else has got this error/solution? I have tried setting my typescript version to the same as the dev dependancy but no luck with that.

**Comment by EddWills95** [comment]
Update: Using version `2.1.6` allows this as noted:

`https://github.com/bergben/ng2-img-tools/issues/23#issuecomment-351318281`
